server:
  port: 9000
  servlet:
    context-path: /api
spring:
  datasource:
    username: mmhtoo
    url: jdbc:mysql://localhost:3306/aop_demo
    password: mmhtoo@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect